name: redarx_angular
description: A starting point for Dart libraries or applications.
version: 0.0.1
author: Me <email@example.com>
homepage: https://github.com/

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  angular2: ^2.2.0
  built_collection: ^1.2.0
  redarx: ^0.6.0

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter
